public with sharing class Line {
    
	public String first{get; set;}
    public String second{get; set;}
    public String third{get; set;}
    public String fourth{get; set;}
    public String fifth{get; set;}
    public String sixth{get; set;}
    public String seventh{get; set;}
    public String eighth{get; set;}
    public String ninth{get; set;}
    public String tenth{get; set;}
    public String eleventh{get; set;}
    public String twelfth{get; set;}
    public String thirteenth{get; set;}
    public String fourteenth{get; set;}
    public String fifteenth{get; set;}
    public String sixteenth{get; set;}
    public String seventeenth{get; set;}
    public String eighteenth{get; set;}
    public String nineteenth{get; set;}
    public String twentieth{get; set;}

    public String twentyFirst{get; set;}
    public String twentySecond{get; set;}
    public String twentyThird{get; set;}
    public String twentyFourth{get; set;}
    public String twentyFifth{get; set;}
    public String twentySixth{get; set;}
    public String twentySeventh{get; set;}
    public String twentyEighth{get; set;}
    public String twentyNinth{get; set;}
    public String thirtieth{get; set;}
    public String thirtyFirst{get; set;}
    public String thirtySecond{get; set;}
    public String thirtyThird{get; set;}
    public String thirtyFourth{get; set;}
    public String thirtyFifth{get; set;}
    public String thirtySixth{get; set;}
    public String thirtySeventh{get; set;}
    public String thirtyEighth{get; set;}
    public String thirtyNinth{get; set;}
    public String fortieth{get; set;}

    public String fortyFirst{get; set;}
    public String fortySecond{get; set;}
    public String fortyThird{get; set;}
    public String fortyFourth{get; set;}
    public String fortyFifth{get; set;}
    public String fortySixth{get; set;}
    public String fortySeventh{get; set;}
    public String fortyEighth{get; set;}
    public String fortyNinth{get; set;}
    public String fiftieth{get; set;}

    public String fiftyFirst{get; set;}
    public String fiftySecond{get; set;}
    public String fiftyThird{get; set;}
    public String fiftyFourth{get; set;}
    public String fiftyFifth{get; set;}
    public String fiftySixth{get; set;}
    public String fiftySeventh{get; set;}
    public String fiftyEighth{get; set;}
    public String fiftyNinth{get; set;}
    public String sixtieth{get; set;}
    
    
}